name: Publish in GitHub Package Registry

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1

      - name: Set GitHub Package Registry and Scope
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install

      - name: Build package files
        run: npm run build

      - name: Publish to GitHub Package Registry
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_PUBLISH_GPR_TOKEN}}
        # GitHub doesn’t honor the GitHub Package Registry URL from above (looks like a bug)
        # Workaround:
        #   - create a local `.npmrc` file defining the registry URL
        #   - then go ahead and publish the package
        run: |
          echo registry=https://npm.pkg.github.com/supercharge >> .npmrc
          npm publish
